const sampleListing = [
    {
        // 
        Disease: "Leaf Blast",
        Observation: "red spots on leaves. (पट्टी पर लाल धब्बबे।)",
        Image: "https://agritech.tnau.ac.in/crop_protection/images/rice_diseases/blast_1.jpg",
        Solution:" 1) Tricyclazole 75%(JU MARS , SWAL TRISTAR) + Isoprothiolane 40% EC (TATA FUJIONE) ",
        Price: "200+400 (RESPECTIVELY) + 550-600/acre",
        Dose: "tricyclazole -> 120gm/acre & Isoprothiolane ->150ml/acre",
        BlogImage:"https://media.istockphoto.com/id/1339849066/photo/cornfield-with-corn-crop-damage-and-cracked-soil-weather-drought-and-flooding-concept.jpg?s=612x612&w=0&k=20&c=wK6edEuhx9p4O3Zq85EPMHbLVa2ZalTmBw7yC3UuzGk=",
        BlogTitle: "What crop to choose in area with water shortage",
        BlogHead:"Growing Millets: The Ideal Crop for Water-Scarce Regions in India",
        BlogPara:"Many regions of India facing water shortages, millets emerge as a reliable and sustainable crop choice. Millets such as bajra (pearl millet), jowar (sorghum), and ragi (finger millet) are not only highly drought-resistant but also require minimal water compared to traditional staples like rice and wheat.Millets thrive in dry, arid climates where other crops may fail. They are known for their deep root systems, which allow them to access moisture from lower soil layers, making them resilient during periods of drought. Additionally, millets have a shorter growing cycle, allowing farmers to harvest them before the dry season intensifies.Apart from being a water-efficient crop, millets are packed with essential nutrients. They are rich in fiber, iron, calcium, and antioxidants, making them a healthier alternative to rice and wheat. Their low glycemic index also makes them suitable for people with diabetes.Millets are economically viable as they require fewer inputs like water and fertilizers, reducing the overall cost of cultivation. Moreover, their ability to grow in poor soil conditions helps in preventing soil degradation and maintaining land fertility over time.",
        
    },
    {
        Disease: "Sheath blight",
        Observation: "rotting of leaves & causes major limitations on rice productio. (पट्टी का गलना।)",
        Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQU5QeUNNdd8Ew9HIJX3gg96bg97vB_6VvkuA&s",
        Solution:"  Hexaconazole 75% WG (JU RAHAT) ",
        Price: "200",
        Dose: "30 gm / acre",
        BlogImage:"https://track2training.com/wp-content/uploads/2021/10/rice.webp?w=1024",
        BlogTitle: "The Importance of Kharif Crops in Indian Agriculture",
        BlogHead:"Kharif Crops: Monsoon-Dependent Staples of Indian Farming",
        BlogPara:"Kharif crops, often referred to as monsoon crops, are a critical component of Indian agriculture, representing a significant portion of the country’s agricultural output. These crops are sown with the arrival of the southwest monsoon in June and harvested in the early autumn months, typically from September to October. Kharif crops rely heavily on monsoon rains, making them essential in regions that receive abundant rainfall. The crops flourish in warm and humid conditions, with temperatures above 25°C and significant water availability during their growth phase.The most prominent Kharif crop is rice, which serves as a staple food for millions of people, especially in regions like West Bengal, Punjab, and Tamil Nadu. Cotton, another major Kharif crop, supports India’s thriving textile industry, while crops like maize, soybean, and pulses such as arhar (pigeon pea) and moong dal are equally important, providing both food and raw materials for various industries. Kharif crops are often grown in tropical and subtropical areas with loamy or clayey soils, ideal for water retention.However, the dependence of Kharif crops on monsoons makes them vulnerable to unpredictable weather patterns. Erratic rainfall, either too much or too little, can severely affect crop yields. Flooding can damage crops during excessive monsoon rains, while delayed or insufficient rains can lead to droughts, affecting both the quantity and quality of production. Climate change has exacerbated these challenges, leading to greater uncertainty for farmers.To counter these issues, advancements in agriculture are promoting sustainable practices such as drought-resistant crop varieties, better irrigation systems like drip irrigation, and improved forecasting of monsoon patterns. By adopting these modern methods, farmers can reduce their dependency on monsoon rains, ensuring the stability of Kharif crop production, which is crucial for India’s food security and economic stability.",
    },
    {
        Disease: "Bacterial Leaf Blight (BLB)",
        Observation: "drying of leaves from top to bottom. (ऊपर से नीचे की तरफ पट्टी का सुखना।)",
        Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRt8pWT85TEAzBwEPqJO5Jx9zG2ZIBxDeRNNQ&s",
        Solution:"  copper oxychloride 50% WP(CRYSTAL – blue copper , TATA - blutox) + PLANTOMYCIN (Arise agro - plantomycin) ",
        Price: " copper oxychloride 50% WP – 250gm/acre + plantomycin -5-10gm /acre",
        Dose: "450 + 50 resp. (overall 500-550 /acre)",
        BlogImage:"https://www.nation.com.pk/print_images/large/2013-01-18/rains-to-have-positive-impact-on-rabi-crops-1358456821-2854.jpg",
        BlogTitle:"The Importance of Rabi Crops in Indian Agriculture",
        BlogHead:"Rabi Crops: The Winter Backbone of Indian Agriculture",
        BlogPara:"Rabi crops, also known as winter crops, play a crucial role in India’s agricultural landscape. These crops are sown at the beginning of the winter season, around October to December, and are harvested in the spring, typically between April and May. Unlike Kharif crops, Rabi crops are not dependent on monsoon rains; instead, they rely on irrigation systems and the residual moisture left in the soil after the monsoon season. The cooler climate during the growing season makes these crops more resilient to pest attacks and diseases.The major Rabi crops grown in India include wheat, barley, mustard, gram, and peas. Wheat is the most important Rabi crop, providing a staple food source for millions of Indians, particularly in northern states like Punjab, Haryana, and Uttar Pradesh. Barley is used for livestock feed and brewing, while mustard is a key oilseed crop, essential for cooking oils. Pulses like gram and peas are rich in protein and serve as important dietary supplements in many Indian households.Rabi crops benefit from a cool growing period, with less evaporation and efficient use of water through irrigation. However, they are vulnerable to unexpected frost or hailstorms during the late winter, which can damage crops just before harvesting. Farmers in India increasingly use modern farming techniques like improved irrigation, soil fertility management, and high-yield crop varieties to increase productivity and reduce risks.Given the stable weather conditions in winter and the widespread availability of irrigation systems, Rabi crops contribute significantly to India’s food security and agricultural economy. With wheat being a major staple and oilseeds like mustard playing a key role in the edible oil industry, Rabi crops are essential for ensuring year-round food production and economic stability in the country.",
    },
    {
        Disease: "Barnyard Grasses (sawa)",
        Observation: " A tufted annual grass, up to 60 cm tall. (एक गुच्छेदार वार्षिक घास, 60 सेमी तक ऊँची।)",
        Image: "https://cdn.britannica.com/91/6291-050-EA01D141/Barnyard-grass.jpg",
        Solution:"Fenoxaprop-p-ethyl 9.3% ec ",
        Price: "350-400",
        Dose: "250ml/acre",
        BlogImage:"https://d1g9yur4m4naub.cloudfront.net/images/Article_Images/ImageForArticle_927_16649735194142678.jpg",
        BlogTitle:"Sustainable Practices for Maintaining Agricultural Land Fertility",
        BlogHead:"Effective Methods to Keep Your Soil Fertile and Productive",
        BlogPara:"Maintaining the fertility of agricultural land is crucial for sustainable farming and long-term productivity. One of the most effective strategies is crop rotation, which involves growing different crops in the same field across successive seasons. This practice helps prevent soil nutrient depletion, as different crops have varying nutrient requirements, and it disrupts the lifecycle of pests and diseases. For instance, planting nitrogen-fixing crops like legumes (peas, beans, or lentils) helps replenish the soil’s nitrogen content naturally, reducing the need for synthetic fertilizers. Incorporating organic matter into the soil is another critical practice. Organic materials, such as compost, animal manure, or decomposed plant matter, are rich in essential nutrients like nitrogen, phosphorus, and potassium, which improve soil structure, increase water retention, and enhance the activity of beneficial microorganisms. These microorganisms break down organic material into usable nutrients for plants, boosting soil fertility over time.Another valuable method is green manuring, where farmers plant cover crops (like clover, rye, or alfalfa) and then plow them back into the soil. These crops not only add organic matter but also protect the soil from erosion, improve its structure, and help suppress weeds. Green manures can increase soil fertility by enhancing nitrogen content and promoting the growth of beneficial organisms. Reducing the use of chemical fertilizers and pesticides is essential for maintaining soil health, as overreliance on chemicals can lead to soil degradation, loss of biodiversity, and pollution of nearby water sources. Instead, adopting biofertilizers (natural fertilizers containing beneficial microbes) and biopesticides (derived from natural organisms) provides a more sustainable alternative, supporting nutrient cycling and plant health without harming the environment.",
    },

    {
        Disease: "Stem-borer (tana chedak)",
        Observation: "stemborer get inside the lower part of the stem and start eating eat (तने का छेदक तने के निचले हिस्से के अंदर घुस जाता है और उसे खाना शुरू कर देता है।)",
        Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQckRYGTnM2lVGjnR61xUOooxIsmIiM7OPYYQ&s",
        Solution:"1)bifenthrin (product that have bifenthrin – hectaStar) ",
        Price: "250-300",
        Dose: "250ml/acre",
        BlogImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjmXg_eHa_AUoWuiVwq9jIhd4GbMoNyJAr7g&s",
        BlogTitle: "Water Harvesting: A Sustainable Approach to Agriculture",
        BlogHead: "Harnessing Rainwater for Efficient Agricultural Practices",
        BlogPara:"Water harvesting is an essential practice in agriculture, especially in regions where water scarcity and irregular rainfall patterns pose significant challenges to farming. It involves the collection and storage of rainwater or runoff, either for immediate use or for later irrigation during dry periods. This technique helps farmers reduce their dependence on unreliable monsoons and over-extraction of groundwater, leading to more sustainable water management and improved crop yields.One common method of water harvesting is through the use of farm ponds, where rainwater is collected in small reservoirs on or near farms. These ponds can be used to irrigate crops during dry spells, ensuring consistent water supply throughout the growing season. Contour bunding is another technique widely used in hilly areas, where ridges or bunds are built along the contours of the land to slow down water runoff, allowing it to seep into the soil and recharge groundwater. This practice prevents soil erosion while improving moisture retention.Check dams are another effective method of water harvesting, especially in semi-arid regions. These small barriers, built across seasonal streams, capture rainwater and prevent it from flowing away quickly, allowing it to percolate into the ground and replenish aquifers. Roof water harvesting, often used in rural areas, captures rainwater from rooftops and channels it into storage tanks or directly into the ground for future use.Water harvesting is not just about storing water; it also plays a crucial role in improving soil health and increasing agricultural productivity. By providing a steady water supply, farmers can grow multiple crops throughout the year, reduce dependency on expensive irrigation systems, and combat the adverse effects of droughts and water shortages. Overall, water harvesting is a sustainable, low-cost solution that supports efficient water use in agriculture while promoting long-term food security.",
    },
    {
        Disease: "Leaf folder",
        Observation: "Leaf folder caterpillars fold a rice leaf around themselves and attach the leaf margins together withsilk strands (पत्ती मोड़क इल्लियाँ चावल की पत्ती को अपने चारों ओर मोड़ लेती हैं और रेशमी धागों से पत्ती के किनारों को आपस में चिपका देती हैं।)",
        Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTn2zoh2K2ffIzXgVc441Fw_F9CK1q2SUXwIQ&s",
        Solution:"1)bifenthrin (product that have bifenthrin – hectaStar) ",
        Price: "250-300",
        Dose: "250ml/acre",
        BlogImage:"https://cdn-images-1.medium.com/max/789/0*7B-7WMBFfIHVEPJG",
        BlogTitle: "Organic vs. Inorganic Farming: A Balanced Comparison",
        BlogHead:"Understanding the Differences Between Organic and Inorganic Farming Practices",
        BlogPara:"Organic and inorganic farming represent two distinct approaches to agriculture, each with its own set of advantages and challenges. Organic farming relies on natural processes and biological inputs to enhance soil fertility, control pests, and grow crops. In contrast, inorganic farming, also known as conventional farming, uses synthetic chemicals, including fertilizers and pesticides, to boost productivity.One of the main advantages of organic farming is its focus on sustainability. Organic practices, such as using compost, green manure, and crop rotation, help maintain soil health over time by improving its structure and nutrient content. Organic farms avoid synthetic chemicals, making their produce healthier and free from harmful pesticide residues. Additionally, organic farming supports biodiversity by encouraging the presence of beneficial organisms like earthworms and pollinators, which contribute to a balanced ecosystem.On the other hand, inorganic farming is often more efficient in terms of yield. The use of chemical fertilizers allows farmers to rapidly replenish essential nutrients in the soil, while pesticides and herbicides effectively control pests and weeds. As a result, inorganic farming can produce large quantities of crops in a shorter period, which is critical for meeting the demands of growing populations. However, these practices can lead to soil degradation, water contamination, and loss of biodiversity over time due to the overuse of chemicals.Ultimately, the choice between organic and inorganic farming depends on factors like environmental impact, crop yield, and long-term sustainability. While inorganic farming may offer short-term gains in productivity, organic farming provides a more sustainable solution that promotes soil health, reduces environmental pollution, and produces healthier food. As global concerns about climate change and sustainability grow, the debate between these two approaches remains central to the future of agriculture.",
    },
    
];
module.exports = { data: sampleListing};